config/routes.rb
    resource :two_factor_authentication, only: [:show, :create, :destroy]

    namespace :two_factor_authentication do
      resources :recovery_codes, only: [:create]
      resource :confirmation, only: [:new, :create]
    end

    resources :identity_proofs, only: [:index, :show, :new, :create, :update]

    resources :applications, except: [:edit] do
      member do
        post :regenerate
      end
    end

    resource :delete, only: [:show, :destroy]
    resource :migration, only: [:show, :create]

    namespace :migration do
      resource :redirect, only: [:new, :create, :destroy]
    end

    resources :aliases, only: [:index, :create, :destroy]
    resources :sessions, only: [:destroy]
    resources :featured_tags, only: [:index, :create, :destroy]
  end

  resources :media, only: [:show] do
    get :player
  end

  resources :tags,   only: [:show]
  resources :emojis, only: [:show]
  resources :invites, only: [:index, :create, :destroy]
  resources :filters, except: [:show]
  resource :relationships, only: [:show, :update]

  get '/public', to: 'public_timelines#show', as: :public_timeline
  get '/media_proxy/:id/(*any)', to: 'media_proxy#show', as: :media_proxy

  resource :authorize_interaction, only: [:show, :create]
  resource :share, only: [:show, :create]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'

    resources :domain_allows, only: [:new, :create, :show, :destroy]
    resources :domain_blocks, only: [:new, :create, :show, :destroy, :update] do
      member do
        get :edit
      end
    end

    resources :email_domain_blocks, only: [:index, :new, :create, :destroy]
    resources :action_logs, only: [:index]
    resources :warning_presets, except: [:new]

    resources :announcements, except: [:show] do
      member do
        post :publish
        post :unpublish
      end
    end

    resource :settings, only: [:edit, :update]

    resources :invites, only: [:index, :create, :destroy] do
      collection do
        post :deactivate_all
      end
    end

    resources :relays, only: [:index, :new, :create, :destroy] do
      member do
        post :enable
        post :disable
      end
    end

    resources :instances, only: [:index, :show], constraints: { id: /[^\/]+/ }

    resources :reports, only: [:index, :show] do
      member do
        post :assign_to_self
        post :unassign
        post :reopen
        post :resolve
      end

      resources :reported_statuses, only: [:create]
    end

    resources :report_notes, only: [:create, :destroy]

    resources :accounts, only: [:index, :show] do
      member do
        post :enable
        post :unsilence
        post :unsuspend
        post :redownload
        post :remove_avatar
        post :remove_header
        post :memorialize
        post :approve
        post :reject
      end

      resource :change_email, only: [:show, :update]
      resource :reset, only: [:create]
      resource :action, only: [:new, :create], controller: 'account_actions'
      resources :statuses, only: [:index, :show, :create, :update, :destroy]
      resources :relationships, only: [:index]

      resource :confirmation, only: [:create] do
        collection do
          post :resend
        end
      end

      resource :role, only: [] do
        member do
          post :promote
          post :demote
        end
      end
    end

    resources :pending_accounts, only: [:index] do
      collection do
        post :approve_all
        post :reject_all
        post :batch
      end
    end

    resources :users, only: [] do
      resource :two_factor_authentication, only: [:destroy]
    end

    resources :custom_emojis, only: [:index, :new, :create] do
      collection do
        post :batch
      end
    end

    resources :account_moderation_notes, only: [:create, :destroy]

    resources :tags, only: [:index, :show, :update] do
      collection do
        post :approve_all
        post :reject_all
        post :batch
      end
    end
  end

  get '/admin', to: redirect('/admin/dashboard', status: 302)

  namespace :api do
    # OEmbed
    get '/oembed', to: 'oembed#show', as: :oembed

    # Identity proofs
    get :proofs, to: 'proofs#index'

    # JSON / REST API
    namespace :v1 do
      resources :statuses, only: [:create, :show, :destroy] do
        scope module: :statuses do
          resources :reblogged_by, controller: :reblogged_by_accounts, only: :index
          resources :favourited_by, controller: :favourited_by_accounts, only: :index
          resource :reblog, only: :create
          post :unreblog, to: 'reblogs#destroy'

          resource :favourite, only: :create
          post :unfavourite, to: 'favourites#destroy'

          resource :bookmark, only: :create
          post :unbookmark, to: 'bookmarks#destroy'

          resource :mute, only: :create
          post :unmute, to: 'mutes#destroy'

          resource :pin, only: :create
          post :unpin, to: 'pins#destroy'
        end

        member do
          get :context
        end
      end

      namespace :timelines do
        resource :home, only: :show, controller: :home
        resource :public, only: :show, controller: :public
        resources :tag, only: :show
        resources :list, only: :show
      end

      resources :streaming, only: [:index]
      resources :custom_emojis, only: [:index]
      resources :suggestions, only: [:index, :destroy]
      resources :scheduled_statuses, only: [:index, :show, :update, :destroy]
      resources :preferences, only: [:index]

      resources :announcements, only: [:index] do
        scope module: :announcements do
          resources :reactions, only: [:update, :destroy]
        end

        member do
          post :dismiss
        end
      end

      resources :conversations, only: [:index, :destroy] do
        member do
          post :read
        end
      end

      resources :media,        only: [:create, :update]
      resources :blocks,       only: [:index]
      resources :mutes,        only: [:index]
      resources :favourites,   only: [:index]
      resources :bookmarks,    only: [:index]
      resources :reports,      only: [:create]
      resources :trends,       only: [:index]
      resources :filters,      only: [:index, :create, :show, :update, :destroy]
      resources :endorsements, only: [:index]
      resources :markers,      only: [:index, :create]

      namespace :apps do
        get :verify_credentials, to: 'credentials#show'
      end

      resources :apps, only: [:create]

      resource :instance, only: [:show] do
        resources :peers, only: [:index], controller: 'instances/peers'
        resource :activity, only: [:show], controller: 'instances/activity'
      end

      resource :domain_blocks, only: [:show, :create, :destroy]
      resource :directory, only: [:show]

      resources :follow_requests, only: [:index] do
        member do
          post :authorize
          post :reject
        end
      end

      resources :notifications, only: [:index, :show] do
        collection do
          post :clear
        end

        member do
          post :dismiss
        end
      end

      namespace :accounts do
        get :verify_credentials, to: 'credentials#show'
        patch :update_credentials, to: 'credentials#update'
        resource :search, only: :show, controller: :search
        resources :relationships, only: :index
      end

      resources :accounts, only: [:create, :show] do
        resources :statuses, only: :index, controller: 'accounts/statuses'
        resources :followers, only: :index, controller: 'accounts/follower_accounts'
        resources :following, only: :index, controller: 'accounts/following_accounts'
        resources :lists, only: :index, controller: 'accounts/lists'
        resources :identity_proofs, only: :index, controller: 'accounts/identity_proofs'

        member do
          post :follow
          post :unfollow
          post :block
          post :unblock
          post :mute
          post :unmute
        end

        resource :pin, only: :create, controller: 'accounts/pins'
        post :unpin, to: 'accounts/pins#destroy'
      end

      resources :lists, only: [:index, :create, :show, :update, :destroy] do
        resource :accounts, only: [:show, :create, :destroy], controller: 'lists/accounts'
      end

      namespace :featured_tags do
        get :suggestions, to: 'suggestions#index'
      end

      resources :featured_tags, only: [:index, :create, :destroy]

      resources :polls, only: [:create, :show] do
        resources :votes, only: :create, controller: 'polls/votes'
      end

      namespace :push do
        resource :subscription, only: [:create, :show, :update, :destroy]
      end

      namespace :admin do
        resources :accounts, only: [:index, :show] do
          member do
            post :enable
            post :unsilence
            post :unsuspend
            post :approve
            post :reject
          end

          resource :action, only: [:create], controller: 'account_actions'
        end

        resources :reports, only: [:index, :show] do
          member do
            post :assign_to_self
            post :unassign
            post :reopen
            post :resolve
          end
        end
      end
    end

    namespace :v2 do
      get '/search', to: 'search#index', as: :search
    end

    namespace :web do
      resource :settings, only: [:update]
      resource :embed, only: [:create]
      resources :push_subscriptions, only: [:create] do
        member do
          put :update
        end
      end
    end
  end

  get '/web/(*any)', to: 'home#index', as: :web

  get '/about',        to: 'about#show'
  get '/about/more',   to: 'about#more'
  get '/terms',        to: 'about#terms'

  match '/', via: [:post, :put, :patch, :delete], to: 'application#raise_not_found', format: false

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  layout 'public'

  before_action :require_open_federation!, only: [:show, :more]
  before_action :set_body_classes, only: :show
  before_action :set_instance_presenter
  before_action :set_expires_in, only: [:show, :more, :terms]

  skip_before_action :require_functional!, only: [:more, :terms]

  def show; end

  def more
    flash.now[:notice] = I18n.t('about.instance_actor_flash') if params[:instance_actor]

    toc_generator = TOCGenerator.new(@instance_presenter.site_extended_description)

    @contents          = toc_generator.html
    @table_of_contents = toc_generator.toc
    @blocks            = DomainBlock.with_user_facing_limitations.by_severity if display_blocks?
  end

  def terms; end

  helper_method :display_blocks?
  helper_method :display_blocks_rationale?
  helper_method :public_fetch_mode?
  helper_method :new_user

  private

  def require_open_federation!
    not_found if whitelist_mode?
  end

  def display_blocks?
    Setting.show_domain_blocks == 'all' || (Setting.show_domain_blocks == 'users' && user_signed_in?)
  end

  def display_blocks_rationale?
    Setting.show_domain_blocks_rationale == 'all' || (Setting.show_domain_blocks_rationale == 'users' && user_signed_in?)
  end

  def new_user
    User.new.tap do |user|
      user.build_account
      user.build_invite_request
    end
  end

  def set_instance_presenter
    @instance_presenter = InstancePresenter.new
  end

  def set_body_classes
    @hide_navbar = true
  end

  def set_expires_in
    expires_in 0, public: true
  end
end

app/views/about/_domain_blocks.html.haml
%table
  %thead
    %tr
      %th= t('about.unavailable_content_description.domain')
      %th= t('about.unavailable_content_description.reason')
  %tbody
    - domain_blocks.each do |domain_block|
      %tr
        %td.nowrap
          %span{ title: domain_block.domain }= domain_block.domain
        %td
          = domain_block.public_comment if display_blocks_rationale?

app/views/about/_login.html.haml
= simple_form_for(new_user, url: user_session_path, namespace: 'login') do |f|
  .fields-group
    - if use_seamless_external_login?
      = f.input :email, placeholder: t('simple_form.labels.defaults.username_or_email'), input_html: { 'aria-label' => t('simple_form.labels.defaults.username_or_email') }, hint: false
    - else
      = f.input :email, placeholder: t('simple_form.labels.defaults.email'), input_html: { 'aria-label' => t('simple_form.labels.defaults.email') }, hint: false

    = f.input :password, placeholder: t('simple_form.labels.defaults.password'), input_html: { 'aria-label' => t('simple_form.labels.defaults.password') }, hint: false

  .actions
    = f.button :button, t('auth.login'), type: :submit, class: 'button button-primary'

  %p.hint.subtle-hint= link_to t('auth.trouble_logging_in'), new_user_password_path

app/views/about/_registration.html.haml
.simple_form__overlay-area{ class: (closed_registrations? && @instance_presenter.closed_registrations_message.present?) ? 'simple_form__overlay-area__blurred' : '' }
  = simple_form_for(new_user, url: user_registration_path, namespace: 'registration') do |f|
    %p.lead= t('about.federation_hint_html', instance: content_tag(:strong, site_hostname))

    .fields-group
      = f.simple_fields_for :account do |account_fields|
        = account_fields.input :username, wrapper: :with_label, label: false, required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.username'), :autocomplete => 'off', placeholder: t('simple_form.labels.defaults.username') }, append: "@#{site_hostname}", hint: false, disabled: closed_registrations?

      = f.input :email, placeholder: t('simple_form.labels.defaults.email'), required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.email'), :autocomplete => 'off' }, hint: false, disabled: closed_registrations?
      = f.input :password, placeholder: t('simple_form.labels.defaults.password'), required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.password'), :autocomplete => 'off' }, hint: false, disabled: closed_registrations?
      = f.input :password_confirmation, placeholder: t('simple_form.labels.defaults.confirm_password'), required: true, input_html: { 'aria-label' => t('simple_form.labels.defaults.confirm_password'), :autocomplete => 'off' }, hint: false, disabled: closed_registrations?

    - if approved_registrations?
      .fields-group
        = f.simple_fields_for :invite_request do |invite_request_fields|
          = invite_request_fields.input :text, as: :text, wrapper: :with_block_label, required: false

    .fields-group
      = f.input :agreement, as: :boolean, wrapper: :with_label, label: t('auth.checkbox_agreement_html', rules_path: about_more_path, terms_path: terms_path), disabled: closed_registrations?

    .actions
      = f.button :button, sign_up_message, type: :submit, class: 'button button-primary', disabled: closed_registrations?

  - if closed_registrations? && @instance_presenter.closed_registrations_message.present?
    .simple_form__overlay-area__overlay
      .simple_form__overlay-area__overlay__content.rich-formatting
        .block-icon= fa_icon 'warning'
        = @instance_presenter.closed_registrations_message.html_safe

app/views/about/more.html.haml
- content_for :page_title do
  = site_hostname

- content_for :header_tags do
  = javascript_pack_tag 'public', integrity: true, crossorigin: 'anonymous'
  = render partial: 'shared/og'

.grid-4
  .column-0
    .public-account-header.public-account-header--no-bar
      .public-account-header__image
        = image_tag @instance_presenter.hero&.file&.url || @instance_presenter.thumbnail&.file&.url || asset_pack_path('media/images/preview.jpg'), alt: @instance_presenter.site_title, class: 'parallax'

  .column-1
    .landing-page__call-to-action{ dir: 'ltr' }
      .row
        .row__information-board
          .information-board__section
            %span= t 'about.user_count_before'
            %strong= number_with_delimiter @instance_presenter.user_count
            %span= t 'about.user_count_after', count: @instance_presenter.user_count
          .information-board__section
            %span= t 'about.status_count_before'
            %strong= number_with_delimiter @instance_presenter.status_count
            %span= t 'about.status_count_after', count: @instance_presenter.status_count
        .row__mascot
          .landing-page__mascot
            = image_tag @instance_presenter.mascot&.file&.url || asset_pack_path('media/images/elephant_ui_plane.svg'), alt: ''

  .column-2
    .contact-widget
      %h4= t 'about.administered_by'

      = account_link_to(@instance_presenter.contact_account)

      - if @instance_presenter.site_contact_email.present?
        %h4
          = succeed ':' do
            = t 'about.contact'

        = mail_to @instance_presenter.site_contact_email, nil, title: @instance_presenter.site_contact_email

  .column-3
    = render 'application/flashes'

    - if @contents.blank? && (!display_blocks? || @blocks&.empty?)
      = nothing_here
    - else
      .box-widget
        .rich-formatting
          = @contents.html_safe

          - if display_blocks? && !@blocks.empty?
            %h2#unavailable-content= t('about.unavailable_content')

            %p= t('about.unavailable_content_html')

            - if (blocks = @blocks.select(&:reject_media?)) && !blocks.empty?
              %p= t('about.unavailable_content_description.rejecting_media')
              = render partial: 'domain_blocks', locals: { domain_blocks: blocks }
            - if (blocks = @blocks.select(&:silence?)) && !blocks.empty?
              %p= t('about.unavailable_content_description.silenced')
              = render partial: 'domain_blocks', locals: { domain_blocks: blocks }
            - if (blocks = @blocks.select(&:suspend?)) && !blocks.empty?
              %p= t('about.unavailable_content_description.suspended')
              = render partial: 'domain_blocks', locals: { domain_blocks: blocks }

  .column-4
    %ul.table-of-contents
      - @table_of_contents.each do |item|
        %li
          = link_to item.title, "##{item.anchor}"

          - unless item.children.empty?
            %ul
              - item.children.each do |sub_item|
                %li= link_to sub_item.title, "##{sub_item.anchor}"

      - if display_blocks? && !@blocks.empty?
        %li= link_to t('about.unavailable_content'), '#unavailable-content'

app/views/about/show.html.haml
- content_for :page_title do
  = site_hostname

- content_for :header_tags do
  %link{ rel: 'canonical', href: about_url }/
  = render partial: 'shared/og'

.landing
  .landing__brand
    = link_to root_url, class: 'brand' do
      = svg_logo_full
      %span.brand__tagline=t 'about.tagline'

  .landing__grid
    .landing__grid__column.landing__grid__column-registration
      .box-widget
        = render 'registration'

      .directory
        - if Setting.profile_directory
          .directory__tag
            = optional_link_to Setting.profile_directory, explore_path do
              %h4
                = fa_icon 'address-book fw'
                = t('about.discover_users')
                %small= t('about.browse_directory')

              .avatar-stack
                - @instance_presenter.sample_accounts.each do |account|
                  = image_tag current_account&.user&.setting_auto_play_gif ? account.avatar_original_url : account.avatar_static_url, width: 48, height: 48, alt: '', class: 'account__avatar'

        - if Setting.timeline_preview
          .directory__tag
            = optional_link_to Setting.timeline_preview, public_timeline_path do
              %h4
                = fa_icon 'globe fw'
                = t('about.see_whats_happening')
                %small= t('about.browse_public_posts')

        .directory__tag
          = link_to 'https://joinmastodon.org/apps', target: '_blank', rel: 'noopener noreferrer' do
            %h4
              = fa_icon 'tablet fw'
              = t('about.get_apps')
              %small= t('about.apps_platforms')

    .landing__grid__column.landing__grid__column-login
      .box-widget
        = render 'login'

      .hero-widget
        .hero-widget__img
          = image_tag @instance_presenter.hero&.file&.url || @instance_presenter.thumbnail&.file&.url || asset_pack_path('media/images/preview.jpg'), alt: @instance_presenter.site_title

        .hero-widget__text
          %p
            = @instance_presenter.site_short_description.html_safe.presence || t('about.about_mastodon_html')
            = link_to about_more_path do
              = t('about.learn_more')
              = fa_icon 'angle-double-right'

        .hero-widget__footer
          .hero-widget__footer__column
            %h4= t 'about.administered_by'

            = account_link_to @instance_presenter.contact_account

          .hero-widget__footer__column
            %h4= t 'about.server_stats'

            %div{ style: 'display: flex' }
              .hero-widget__counter{ style: 'width: 50%' }
                %strong= number_to_human @instance_presenter.user_count, strip_insignificant_zeros: true
                %span= t 'about.user_count_after', count: @instance_presenter.user_count
              .hero-widget__counter{ style: 'width: 50%' }
                %strong= number_to_human @instance_presenter.active_user_count, strip_insignificant_zeros: true
                %span
                  = t 'about.active_count_after'
                  %abbr{ title: t('about.active_footnote') } *

app/views/about/terms.html.haml
- content_for :page_title do
  = t('terms.title', instance: site_hostname)

.grid
  .column-0
    .box-widget
      .rich-formatting= @instance_presenter.site_terms.html_safe.presence || t('terms.body_html')
  .column-1
    = render 'application/sidebar'